name: deploy to lambda
on: 
  push:
    branches:
      - main
jobs:

  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node.js setup
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.x

      - name: Build
        run: |
          npm ci
          zip -r -9 function.zip *
          
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: HillcroftGetPurchases
          zip_file: function.zip
          source: index.js
